### ISSUE TITLE
Units and correct number format missing for some sensors

### ISSUE THREAD

**Issue by kreativhuhn** [CestLaGalere/mobilealerts#25]
Hi,
while e.g. temperature and humidity sensor data contain a correct number format and units, this is not the case for some other sensors.
I encounter these problems with air pressure (ap), wind speed (ws), wind gusts (wg).

Also the units are not always the same as you have written into the table on the readme file. Units for temperature sensors, rain and wind speed + gusts can be selected in the settings of the Mobile Alerts app. E.g. I'm using kn for wind speeds.

Would be great if you could fix those issues.
Thanks a lot for developing this integration!

- Stef

**Comment by petrleocompel** [comment]
From this... I guess we will just only inform that - unit is set up in Mobile APP. 
I guess that will be enough and if somebody wants different units in HA we will just redirect them to "templates" https://www.home-assistant.io/integrations/template/ and helpers (cannot find helpers page right now)

So that will be enough?

**Comment by CestLaGalere** [comment]
Yes - changed units are only stored and displayed on the phone - the sensors do not store or transmit any different units.
I doubt any development will be put into providing this as there is already a solution.
@kreativhuhn see above - you will need to do this in the HA front end.
